// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function run() {
  return Curry._1(Pervasives.print_endline, "Hello world");
}

exports.run = run;
/* No side effect */
